Gleon99/windows
Infinidat/fscmp pull request #17
Opened 2020-02-16 13:46 UTC by gleon99

2020-02-16 13:51 UTC, gleon99 commented on src/cmp/comparison.rs
>  pub enum Diff {
An alternative I had considered is having a separate `Diff` enum. Thus, all these `#[cfg(...` macros would be avioded, but then there would be code duplication in everything related `Contents`. I thought that current implenetation is better.

2020-02-16 13:51 UTC, gleon99 commented on src/cmp/mod.rs
> -            ..Default::default()
It had to be done, otherwise it wouldn't compile.

2020-02-16 13:53 UTC, gleon99 commented on src/cmp/mod.rs
> +                .custom_flags(winapi::um::winbase::FILE_FLAG_NO_BUFFERING)
`FILE_FLAG_NO_BUFFERING` is like `O_DIRECT`.

2020-02-16 14:07 UTC, drrlvn requested changes

2020-02-16 14:07 UTC, drrlvn commented on src/cmp/mod.rs
>          let dir = Dir::open(path.parent().unwrap())?;
Merge these `let` statements into one so that only a single `#[cfg(unix)]` is needed.

2020-02-16 17:16 UTC, gleon99 commented on src/cmp/mod.rs
>          let dir = Dir::open(path.parent().unwrap())?;
Partially fixed that. Merged the statements into 2. Can't merge into a single one, because`dir` is needed to initialize `metadata`.

2020-02-17 07:50 UTC, drrlvn approved these changes

2020-02-17 07:50 UTC, merged